from bench.view.discuss import (
    display_discuss_error,
    display_discuss_list,
    display_discuss_start,
)
from bench.view.init import (
    display_agents_populating,
    display_agents_population_warning,
    display_init_error,
    display_init_success,
)
from bench.view.populate import (
    display_populate_agents_error,
    display_populate_agents_start,
    display_populate_agents_warning,
)
from bench.view.source import (
    display_source_added,
    display_source_error,
    display_source_list,
    display_source_removed,
    display_source_updated,
)
from bench.view.status import display_status
from bench.view.task import (
    display_task_completed,
    display_task_created,
    display_task_error,
    display_task_implement_complete,
    display_task_implement_phase_complete,
    display_task_implement_phase_start,
    display_task_implement_start,
    display_task_list,
    display_task_refine_start,
)
from bench.view.workbench import (
    display_script_completed,
    display_script_failed,
    display_script_not_executable,
    display_script_running,
    display_workbench_activated,
    display_workbench_created,
    display_workbench_deleted,
    display_workbench_error,
    display_workbench_list,
    display_workbench_retired,
    display_workbench_updated,
)

__all__ = [
    "display_agents_populating",
    "display_agents_population_warning",
    "display_discuss_error",
    "display_discuss_list",
    "display_discuss_start",
    "display_init_error",
    "display_init_success",
    "display_populate_agents_error",
    "display_populate_agents_start",
    "display_populate_agents_warning",
    "display_source_added",
    "display_source_error",
    "display_source_list",
    "display_source_removed",
    "display_source_updated",
    "display_status",
    "display_task_completed",
    "display_task_created",
    "display_task_error",
    "display_task_implement_complete",
    "display_task_implement_phase_complete",
    "display_task_implement_phase_start",
    "display_task_implement_start",
    "display_task_list",
    "display_task_refine_start",
    "display_script_completed",
    "display_script_failed",
    "display_script_not_executable",
    "display_script_running",
    "display_workbench_activated",
    "display_workbench_created",
    "display_workbench_deleted",
    "display_workbench_error",
    "display_workbench_list",
    "display_workbench_retired",
    "display_workbench_updated",
]
